UI.MVC/Controllers/Api/SongsController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using MusicManager.BL;
using MusicManager.BL.Domain;
using UI.MVC.Models;

namespace UI.MVC.Controllers.Api
{
    [Route("api/[controller]")]
    public class SongsController : ControllerBase
    {
        private readonly IManager _manager;

        public SongsController(IManager manager)
        {
            _manager = manager;
        }
        
        // GET
        [HttpGet("ofArtist/{id}")]
        public IActionResult GetSongsOfArtist(int id)
        {
            if (!_manager.GetSongsOfArtist(id).Any())
            {
                return NoContent();
            }

            
            
            return Ok(MapSongsToSongDtos(_manager.GetSongsOfArtist(id)));
        }
        
        [HttpGet("notOfArtist/{id}")]
        public IActionResult GetSongsNotOfArtist(int id)
        {
            if (!_manager.GetSongsNotOfArtist(id).Any())
            {
                return NoContent();
            }
            
            return Ok(MapSongsToSongDtos(_manager.GetSongsNotOfArtist(id)));
        }

        [HttpGet]
        public IActionResult Get()
        {
            if (!_manager.GetAllSongs().Any())
            {
                return NoContent();
            }
            
            return Ok(_manager.GetAllSongs());
        }

        // Song - SongDto mapping

        private IEnumerable<SongDto> MapSongsToSongDtos(IEnumerable<Song> songs)
        {
            IList<SongDto> songDtos = new List<SongDto>();
            foreach(Song song in songs)
            {
                songDtos.Add(MapSongToSongDto(song));
            }

            return songDtos;
        }

        private SongDto MapSongToSongDto(Song song)
        {
            SongDto songDto = new SongDto()
            {
                Id = song.Id,
                Title = song.Title,
                AmountOfStreams = song.AmountOfStreams,
                ReleaseDate = song.ReleaseDate,
                Length = song.Length,
                Genre = song.Genre
            };

            return songDto;
        }
    }
}

UI.MVC/Controllers/ArtistController.cs
using Microsoft.AspNetCore.Mvc;
using MusicManager.BL;

namespace UI.MVC.Controllers
{
    public class ArtistController : Controller
    {
        private readonly IManager _manager;

        public ArtistController(IManager manager)
        {
            _manager = manager;
        }
        
        // GET
        public IActionResult Detail(int id)
        {
            return View(_manager.GetArtistWithRecordLabelAndManager(id));
        }
    }
}

UI.MVC/Controllers/SongController.cs
using Microsoft.AspNetCore.Mvc;
using MusicManager.BL;
using MusicManager.BL.Domain;

namespace UI.MVC.Controllers
{
    public class SongController : Controller
    {
        private readonly IManager _manager;

        public SongController(IManager manager)
        {
            _manager = manager;
        }
        
        // GET
        public IActionResult Index()
        {
            return View(_manager.GetAllSongs());
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        
        [HttpPost]
        public IActionResult Add(Song song)
        {
            if (!ModelState.IsValid)
            {
                return View(song);
            }
            
            Song createdSong = _manager.AddSong(song.Title, song.AmountOfStreams, song.ReleaseDate, song.Length, null, song.Genre);
            
            return RedirectToAction("Detail","Song",new {id = createdSong.Id});
        }

        public IActionResult Detail(int id)
        {
            return View(_manager.GetSongWithArtists(id));
        }
    }
}

UI.MVC/Views/Song/Add.cshtml
@using MusicManager.BL.Domain
@model MusicManager.BL.Domain.Song

@{
    ViewBag.Title = "Add Song";
    Layout = "_Layout";
}

<h1>Add Song</h1>

<article>
    <form asp-controller="Song" asp-action="Add" method="post">
        <div class="form-group">
            <label asp-for="Title">Title</label>
            <input asp-for="Title" type="text" class="form-control">
        </div>
        <span class="text-danger" asp-validation-for="Title"></span>
        <div class="form-group">
            <label asp-for="Length">Length</label>
            <input class="form-control" asp-for="Length" type="text"/>
        </div>
        <span class="text-danger" asp-validation-for="Length"></span>
        <div class="form-group">
            <label asp-for="ReleaseDate">Release date</label>
            <input class="form-control" asp-for="ReleaseDate" type="date"/>
        </div>
        <span class="text-danger" asp-validation-for="ReleaseDate"></span>
        <div class="form-group">
            <label asp-for="AmountOfStreams"># Streams</label>
            <input asp-for="AmountOfStreams" type="number" class="form-control">
        </div>
        <span class="text-danger" asp-validation-for="AmountOfStreams"></span>
        <div class="form-group">
            <label asp-for="Genre">Genre</label>
            <select class="form-control" asp-for="Genre">
                @foreach (var genre in Html.GetEnumSelectList<Genre>())
                {
                    <option>@genre.Text</option>
                }
            </select>
        </div>
        <span class="text-danger" asp-validation-for="Genre"></span>
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</article>

UI.MVC/Views/Song/Detail.cshtml
@model MusicManager.BL.Domain.Song

@{
    ViewBag.Title = "Song Detail";
    Layout = "_Layout";
}

<h1>Song Detail</h1>

<article>
    <table class="table table-borderless">
        <tr>
            <th scope="col">Title</th>
            <td>@(Model.Title ?? "Empty")</td>
        </tr>
        <tr>
            <th scope="col">Length</th>
            <td>@Model.Length.ToString("mm':'ss")</td>
        </tr >
        <tr>
            <th scope="col">Release date</th>
            <td>@Model.ReleaseDate.ToString("dd/MM/yyyy")</td>
        </tr>
        <tr>
            <th scope="col"># Streams</th>
            <td>@(Model.AmountOfStreams == null ? "None" : Model.AmountOfStreams)</td>
        </tr>
        <tr>
            <th scope="col">Genre</th>
            <td>@Model.Genre</td>
        </tr>
    </table>
</article>


<h2>Artists</h2>

<article>
    <table class="table">
        <tr>
            <th scope="col">Alias</th>
            <th scope="col"># Followers</th>
            <th scope="col"></th>
        </tr>
        @foreach (var songContribution in Model.SongContributions)
        {
            var parms = new Dictionary<string, string>
                {
                    { "artistId", $"{songContribution.Artist.Id}" },
                };

            <tr>
                <td>@(songContribution.Artist.Alias ?? "Empty")</td>
                <td>@songContribution.Artist.AmountOfFollowers</td>
                <td><a class="" asp-area="" asp-controller="Artist" asp-all-route-data="parms" asp-action="Detail" asp-route-id="@songContribution.Artist.Id">Details</a></td>
            </tr>
        }
    </table>
</article>

UI.MVC/Views/Song/Index.cshtml
@model IEnumerable<MusicManager.BL.Domain.Song>

@{
    ViewBag.Title = "All Songs";
    Layout = "_Layout";
}

<h1>All Songs</h1>

<article>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Title</th>
                <th scope="col">Length</th>
                <th scope="col"># Streams</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
        @foreach (var song in Model)
        {
            <tr>
                <td>@(song.Title ?? "Empty")</td>
                <td>@song.Length.ToString("mm':'ss")</td>
                <td>@(song.AmountOfStreams == null ? "None" : song.AmountOfStreams)</td>
                <td><a class="" asp-area="" asp-controller="Song" asp-action="Detail" asp-route-id="@song.Id">Details</a></td>
            </tr>
        }
        </tbody>
    </table>
</article>